### ISSUE TITLE
USER STORY: Event Filtering

### ISSUE THREAD

**Issue by jdohertydev** [jdohertydev/runit#7]
**EPIC 1: Event Discovery and Browsing #1 ** 

As a **runner**, I want **to filter events by categories so that I can narrow down the list to relevant races.**

**Acceptance Criteria**

- Users can filter events by categories such as road race, trail or mixed.
- Filtered events are displayed correctly according to the selected categories.

**Tasks**

- [x] Create filter options for users.
- [x] Implement filtering logic in backend views.
- [x] Develop frontend interface for selecting and applying filters.
